language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install nose pylint
# command to run tests
script:
  - echo "TODO: to be done"
  # - find . -name "*.py" | xargs pylint -E
